Feature/imageSlide
reboot-badminton/reboot-homepage pull request #1
Opened 2024-07-13 13:34 UTC by judiking1

1. page.tsx 에 slideImages 라는 srcs 배열 생성
2. ImageSlide.tsx 수정
3. BlurredImage.tsx 수정
4. public/slide 폴더 생성 및 예시 이미지 19개 복제

2024-07-13 17:33 UTC, CubeDr requested changes

2024-07-13 17:33 UTC, CubeDr commented on app/components/BlurredImage.tsx
> +import Image from "next/image";
작은 따옴표

2024-07-13 17:33 UTC, CubeDr commented on app/components/BlurredImage.tsx
> +        alt={`blured badminton${src}`}
alt text는 Props에서 같이 넘겨받도록 합시다

2024-07-13 17:33 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +import { useState, useEffect } from "react";
작은 따옴표

2024-07-13 17:33 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +};
이 부분 원래대로 해주십쇼

2024-07-13 17:33 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +  const [isHovered, setIsHovered] = useState<boolean>(false);
`0`, `false`처럼 자료형이 명확하면 굳이 타입 명시하지 않아도 됩니다.
`null`이 가능한 경우처럼 자료형이 제대로 추론되기 어려울 경우에만 명시해주세요.

2024-07-13 17:33 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +  };
`useCallback`을 사용해봅시다.

2024-07-13 17:33 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +  };
23-40줄에 세미콜론이 빠져있는데 추가해 주세요.

2024-07-13 17:33 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +                : "bg-gray-300 rounded-xl"
`rounded-xl`은 공통이니 분기에서 빼줍시다.

2024-07-13 17:33 UTC, CubeDr commented on app/page.tsx
> +const slideImages = Array.from({ length: 19 }, (_, index) => (index + 1).toString());
여기에서 `slide/` 까지 같이 넣어주세요. `ImageSlide`는 어떤 이미지든 받을 수 있는 범용적인 컴포넌트가 되어야 합니다.

2024-07-14 10:13 UTC, CubeDr requested changes

2024-07-14 10:13 UTC, CubeDr commented on app/components/BlurredImage.tsx
> +export default function BlurredImage({ imageProps }: { imageProps: ImageProps }) {
`ImageProps` 그대로 안 쓰고 한 번 감싼 이유가 있나요?

2024-07-14 10:13 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +'use client'
`'use client'` 밑에 한 줄 띄워주세요

2024-07-14 10:13 UTC, CubeDr commented on app/components/ImageSlide.tsx
> +    if (!isHovered) {
조건 반전시켜서 인덴트 하나 줄여주세요.
```
if (isHovered) return;

const interval = ...
```

2024-07-14 10:31 UTC, judiking1 commented on app/components/BlurredImage.tsx
> +export default function BlurredImage({ imageProps }: { imageProps: ImageProps }) {
이렇게 안쓰면 에러가 발생합니다.

2024-07-14 10:50 UTC, CubeDr approved these changes

2024-07-14 10:50 UTC, merged