Input #1 Date, Phone Number
reboot-badminton/reboot-homepage pull request #10
Opened 2024-07-14 16:41 UTC by judiking1

![image](https://github.com/user-attachments/assets/81e29531-6b3d-4ed7-bde7-265662ff9ea2)

![image](https://github.com/user-attachments/assets/64bf168f-1810-4246-9beb-6dad6a5d2857)

![image](https://github.com/user-attachments/assets/98ea22f3-5400-4c6c-bdd8-42872c4b47f6)

![image](https://github.com/user-attachments/assets/f6a7c406-8893-4a45-95f7-68aff6128a34)

2024-07-14 16:51 UTC, CubeDr requested changes

2024-07-14 16:51 UTC, CubeDr commented on app/components/BlurredImage.tsx
> +      <Image src={src} alt={alt} fill priority className="object-contain" />
여기 `priority`를 두면 슬라이드에 있는 모든 이미지가 priority가 됩니다.
첫 번째 이미지에만 priority를 붙이는 것이 성능상 좋을 것 같습니다.

2024-07-14 16:51 UTC, CubeDr commented on app/register/DateFieldInput.tsx
> +interface Props {
위에 한 줄 띄워주세요

2024-07-14 16:51 UTC, CubeDr commented on app/register/DateFieldInput.tsx
> +  const [selectedDate, setSelectedDate] = useState<Date | null>(field.value);
`null`이 가능한가요?

2024-07-14 16:51 UTC, CubeDr commented on app/register/DateFieldInput.tsx
> +        minDate={new Date()} // 오늘 이전의 날짜 선택 불가능하게 설정
생년월일은 무조건 오늘 이전 날짜 아닌가요?

2024-07-14 16:51 UTC, CubeDr commented on app/register/PhoneNumberFieldInput.tsx
> +
빈 줄 한 줄로 줄여주세요

2024-07-14 16:51 UTC, CubeDr commented on app/register/PhoneNumberFieldInput.tsx
> +      setError(null); // Clear error if the format is valid
중복되는 주석 지워주세요

2024-07-14 16:51 UTC, CubeDr commented on app/register/PhoneNumberFieldInput.tsx
> +    // Set error if the format is invalid
주석 지워주세요

2024-07-14 16:51 UTC, CubeDr commented on app/register/PhoneNumberFieldInput.tsx
> +  const parsingPhoneNumber = useCallback((num: string) => {
`parsePhoneNumber`

2024-07-14 16:51 UTC, CubeDr commented on app/register/PhoneNumberFieldInput.tsx
> +  },[]);
아래 한 줄 띄워주세요

2024-07-14 16:59 UTC, judiking1 commented on app/register/DateFieldInput.tsx
> +  const [selectedDate, setSelectedDate] = useState<Date | null>(field.value);
DatePicker의 onChange에서 null값을 받을 수도 있다고 설명이 나와있는것같은데.. 저 애들을 지우면 onchange에서 에러가 뜨더라고요

2024-07-14 17:08 UTC, CubeDr commented on app/register/DateFieldInput.tsx
> +  const [selectedDate, setSelectedDate] = useState<Date | null>(field.value);
어떨 때 null인가요? 날짜 선택 안됐을 때 null이라면 selectedDate에 아예 넣으면 안되는 것 아닌가요?

2024-07-14 17:14 UTC, CubeDr requested changes

2024-07-14 17:14 UTC, CubeDr commented on app/register/PhoneNumberFieldInput.tsx
> -    // Remove all non-digit characters
이 주석은 살려주세요.
주석의 기준은 코드를 읽으면서 바로 의미가 읽히느냐인데, 그렇지 않은 대표적인 예가 정규표현식입니다.
마찬가지로 아래 전화번호 정규표현식 주석도 살려주세요.

2024-07-14 17:15 UTC, CubeDr requested changes

2024-07-14 17:15 UTC, CubeDr commented on app/register/DateFieldInput.tsx
> +        maxDate={new Date()} // 오늘 이전의 날짜 선택 불가능하게 설정
주석 지워주세요

2024-07-14 17:19 UTC, judiking1 commented on app/register/DateFieldInput.tsx
> +  const [selectedDate, setSelectedDate] = useState<Date | null>(field.value);
이 부분은 저도 잘 모르겠씁니다. 에러로만 나타나서 DatePicker 에서 그냥 type을 그렇게 정해놓은것같은데..

2024-07-14 17:23 UTC, CubeDr commented on app/register/DateFieldInput.tsx
> +  const [selectedDate, setSelectedDate] = useState<Date | null>(field.value);
어떨 때 null이 되는지, selectedDate가 null이어도 되는지, 된다면 null일 때 어떻게 표시할 것인지를 한 번 생각해 보셔야 할 것 같습니다. 머지는 그 이후에 합시다.

2024-07-15 14:06 UTC, CubeDr requested changes

2024-07-15 14:06 UTC, CubeDr commented on app/register/DateFieldInput.tsx
> +      if (date !== null) {
1. `null` 검사는 `!==` 대신 `!=`으로 해주세요.
2. 조건 반전시켜서 인덴트 하나 줄여주세요. (early-out)

2024-07-15 14:06 UTC, CubeDr commented on app/register/PhoneNumberFieldInput.tsx
> +    if (match) {
조건을 반전시켜서 예외 로직을 먼저 검사해주세요.
```
if (match == null) {
  setError('유효하지 않은 전화번호');
  return num;
}

const [. areaCode, ...
```

2024-07-16 13:34 UTC, CubeDr approved these changes

2024-07-16 13:39 UTC, merged