Registrations
reboot-badminton/reboot-homepage pull request #12
Opened 2024-07-18 08:59 UTC by judiking1

![image](https://github.com/user-attachments/assets/10f78c26-81cb-43ff-984e-8e35665ed71b)

![image](https://github.com/user-attachments/assets/92ec0794-8d98-4afd-ad24-8143af0b8056)

2024-07-19 11:37 UTC, CubeDr requested changes

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/getRegistration.ts
> +export function formatDate(timestamp: Timestamp) {
registration과 관련 없으니 date_util.ts 처럼 별도의 파일로 분리 바랍니다.

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/getRegistration.ts
> +    console.log('Registration updated successfully');
console.log 지워주세요

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/getRegistration.ts
> +import { doc, Timestamp, updateDoc } from "firebase/firestore";
작은 따옴표로 바꾸고 변경된 파일들 리포맷 해주세요

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/getRegistration.ts
> +export const updateRegistration = async (registrationId: string, updatedData: Partial<RegistrationDataType>) => {
여기 `Partial` 들어가야 합니까?

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +    window.alert('슬롯이 업데이트되었습니다.');
`window.alert` 말고 `Dialog` 사용해주세요.
TimeSlotFieldInput.tsx와 TimeSlotSelectDialog.tsx 참고.

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +const handleAccept = async (slot: TimeSlot, registrationName: string) => {
`registrationName` -> `name`

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        window.alert('신청서에서 슬롯이 삭제되었습니다.');
`Dialog` 사용해 주세요.

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +          (_: TimeSlot, i: number) => i !== index
`filter()`에 데이터 타입 생략해주세요.
`(_, i) => i !== index`

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +                            console.log('수락합니다.');
`console.log` 지워주세요

2024-07-19 11:37 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        await updateRegistration(registration.id, { times: [...updatedTimes] });
이러면 아예 데이터가 삭제되는 것 아닌가요? 데이터 날리지 말고 수락/거절 여부만 저장해주세요.

2024-07-20 02:15 UTC, judiking1 commented on app/manage/registrations/page.tsx
> +          (_: TimeSlot, i: number) => i !== index
![image](https://github.com/user-attachments/assets/55b05f53-70f1-4a4f-b40d-9eaa306468a3)

타입생략하면 빨간줄 뜨던데 괜찮나요?

2024-07-20 02:30 UTC, CubeDr requested changes

2024-07-20 02:30 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +          (_: TimeSlot, i: number) => i !== index
`RegistrationDataType`에서 값이 `any`로 되어있어서 그렇습니다. 사용할 자료형만 명시해주세요

2024-07-20 11:41 UTC, CubeDr requested changes

2024-07-20 11:41 UTC, CubeDr commented on app/manage/registrations/date_utils.ts
> +import { Timestamp } from 'firebase/firestore';
registration이랑 상관 없으니 `app/`으로 옮겨주세요

2024-07-20 11:41 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +      }));
`isRegistered`로 필터 걸어야 하지 않나요? 이미 응답한것도 다 보이는 거 아닌가요?

2024-07-20 11:41 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        );
`handleAccept`와 `handleReject`에 `isRegistered` 부분만 빼고 나머지는 모두 동일하니 함수 합쳐주세요

2024-07-20 11:41 UTC, CubeDr commented on app/manage/registrations/getRegistration.ts
> +  }
여기 `try-catch`가 의미 없는 것 같습니다. 에러를 처리하는 것도 아니고 그냥 로그만 찍고 있어서 오히려 호출부에서 에러 처리하기 어려워지기만 합니다.

그냥 `await updateDoc(...)` 호출하는 걸로만 바꿔주세요.

2024-07-20 11:41 UTC, CubeDr commented on app/manage/registrations/RegistrationSelectDialog.tsx
> +'use client';
이거 `use client` 있어야 하나요?

2024-07-20 13:50 UTC, judiking1 commented on app/manage/registrations/page.tsx
> +      }));
응답한거라도 일단 어떤 수업 시간 희망했는지 나타내고 isRegistered 있으면 수락/거절 버튼을 숨기는건 어떨까요?

2024-07-20 13:53 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +      }));
그러면 적어도 아직 응답 안한걸 위에 보여주세요

2024-07-21 02:23 UTC, CubeDr requested changes

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/RegistrationSelectDialog.tsx
> +function RegistrationDecisionDialog({ text, onConfirm }: Props) {
`<Dialog>`에 `<ConfirmDialogButton>`을 사용한거랑 차이가 없어보입니다. Registration 특정한 로직도 없구요.

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +      index: number,
`index`가 무엇을 뜻하는지를 함수 원형만 보고 알 수 없습니다.
`timeIndex`처럼 의미를 알 수 있는 이름으로 변경해주세요.

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        // updatedTimes 배열을 정렬
`updatedTimes.sort()`를 읽으면 정렬이라는 것은 알 수 있습니다. 주석 지워주세요.

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        // updatedTimes 배열을 정렬
그런데 정렬이 왜 필요한가요?

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +    fetchRegistrations();
여러 요청에 대해서 수락을 눌렀을 때 제대로 업데이트 되나요??
이미 '수락되었습니다'가 들어간 상태에서 다시 다른 요청에 대해 '수락되었습니다'를 누르면 리렌더링이 안일어날 것 같은데요

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +                <div>{registration.name || '-'}</div>
`||` 대신 `??`을 써주세요. 아래도 마찬가지입니다.

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +                        {slot.isRegistered !== undefined && (
`undefined`나 `null`은 동등 연산자 쓰지 말아주세요.
`!= null`로 바꿔주세요.

2024-07-21 02:23 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +                      {slot.isRegistered == undefined && (
`== null`

2024-07-21 03:48 UTC, judiking1 commented on app/manage/registrations/page.tsx
> +        // updatedTimes 배열을 정렬
응답안한걸 위로 올리라고 하셔서 여기서 정렬해서 업데이트해봤습니다..

2024-07-21 03:49 UTC, judiking1 commented on app/manage/registrations/page.tsx
> +    fetchRegistrations();
정확하십니다.

2024-07-21 04:10 UTC, CubeDr requested changes

2024-07-21 04:10 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        // updatedTimes 배열을 정렬
이렇게 해버리면 registration 로직이랑 상관 없어 보이는 데이터들이 전부 영향을 받게 됩니다.
보여줄 때만 정렬해서 보여주세요.

2024-07-22 13:31 UTC, CubeDr requested changes

2024-07-22 13:31 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +      {isSuccess && <Dialog text={dialogText} useDotAnimation={false} />}
`isSuccess`인데 `dialogText`가 없는 경우도 있나요?
아니면 반대로 `dialogText`는 있는데, `isSuccess`는 `false`인 경우도 있나요?

여기 코드만 보면 `isSuccess`이면 `dialogText`가 있고, 그러면 다이얼로그를 보여주는 것 같은데, `isSuccess`가 필요한가요?

2024-07-22 13:31 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +          i === slotIndexToUpdate ? { ...time, isRegistered: isAccepted } : time
`slotIndexToUpdate`는 `registration.times`에 대한 인덱스입니다. `registration.times`에는 `slot`이란 말이 없습니다.
`timeIndex`나 `timeSlotIndex`등 `time`에 대한 것이라는 걸 명확히 해주세요.

2024-07-22 13:31 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +          registrationData.times.sort((a, b) => {
처리하지 않은 요청을 먼저 보기 위함이라 정렬은 적합하지 않습니다. 이 상황에서 정렬을 써버리면 코드를 읽기 힘들어지고, 부작용이 생길 수 있습니다.
1. 정렬은 전체 데이터를 오름차순 혹은 내림차순으로 정렬할 때 사용합니다. 지금은 그냥 특정 데이터를 앞에 놓기 위함이므로 정렬을 보면 혼란스러워집니다.
2. 대부분의 정렬은 stable하지 않습니다. 즉, 우선순위가 같은 데이터들의 순서가 유지되지 않아 아주 오래된 요청이 위로 올라오게 될 수 도 있습니다.

`filter`를 사용해서 처리해주세요.

2024-07-22 13:31 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        }, 1000);
1초를 기다리는 것이 은근 사용자 경험을 크게 저하시킵니다. 다이얼로그에 confirm 버튼 추가해서 닫아주세요.

2024-07-22 13:31 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +        await updateRegistration(registration.id, { times: updatedTimes });
업데이트 하기 전 로딩 다이얼로그 표시 -> 업데이트 후 완료 다이얼로그 표시 해주세요.

2024-07-22 14:55 UTC, judiking1 commented on app/manage/registrations/page.tsx
> +          registrationData.times.sort((a, b) => {
저를 또한번 깨우치게 해주는 리뷰입니다.

2024-07-22 14:55 UTC, judiking1 commented on app/manage/registrations/page.tsx
> +        }, 1000);
사용자 경험에 대해 하나 배워갑니다

2024-07-22 16:26 UTC, CubeDr requested changes

2024-07-22 16:26 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +const UPDATING_TEXT = '업데이트 중입니다...';
Dialog에 useDotAnimation 설정하면 ... 생기니까 여기에선 빼주세요. 이렇게 하면 점이 6개 찍힐 듯 합니다.

2024-07-22 16:26 UTC, CubeDr commented on app/manage/registrations/page.tsx
> +const NOTACCEPT_TEXT = '거절 완료했습니다';
REJECT_TEXT

2024-07-22 16:32 UTC, merged