#1 로그인
reboot-badminton/reboot-homepage pull request #17
Opened 2024-09-22 05:57 UTC by judiking1

2024-09-22 06:03 UTC, CubeDr commented
메인 페이지 푸터에서 이 페이지로 이동하는 버튼도 추가해주세요.

2024-09-22 06:03 UTC, CubeDr requested changes

2024-09-22 06:03 UTC, CubeDr commented on app/login/page.tsx
> +  async function handleSuccessfulLogin(user: any) {
`user` 타입 지정해주세요

2024-09-22 11:51 UTC, judiking1 commented
Auth 브랜치의 LogIn.tsx가 이 페이지로 이동하는 버튼을 나타냅니다.
LogIn.tsx는 layout.tsx 에서 푸터안에 넣었습니다.

2024-09-22 13:16 UTC, CubeDr commented
> Auth 브랜치의 LogIn.tsx가 이 페이지로 이동하는 버튼을 나타냅니다. LogIn.tsx는 layout.tsx 에서 푸터안에 넣었습니다.

그러면 그 LogIn.tsx를 이 PR로 옮겨주세요.

2024-09-22 13:24 UTC, judiking1 commented
Login.tsx에 유저 정보를 받아와야 로그인, 로그아웃, 관리자페이지를 구분해서 표시하는데,

Auth 브랜치에서 유저정보를 받게 하고 있어서 거기에 전부 적은 것인데 여기로 옮겨야 하나요?

2024-09-22 13:41 UTC, CubeDr commented
> Login.tsx에 유저 정보를 받아와야 로그인, 로그아웃, 관리자페이지를 구분해서 표시하는데,
> 
> Auth 브랜치에서 유저정보를 받게 하고 있어서 거기에 전부 적은 것인데 여기로 옮겨야 하나요?

회원가입 없어도 로그인, 로그아웃, 관리자 페이지 구분 되지 않나요?

로그인만 되어있는 경우 => 로그아웃 표시
로그인 && role == 'admin'이나 'manager' 인 경우 => 관리자 페이지, 로그아웃 표시
로그인 안 되어 있는 경우 -> 로그인 표시

2024-09-23 01:30 UTC, CubeDr requested changes

2024-09-23 01:30 UTC, CubeDr commented on app/components/LogIn.tsx
> +    </>
스크린샷 부탁드립니다

2024-09-23 01:30 UTC, CubeDr commented on app/components/LogIn.tsx
> +enum SignInStatus {
`SignInStatus`는 로그인 돼있는지, 아닌지만 나타나는 듯 하니까 `Role` 같은걸로 이름을 바꾸는게 나을 것 같습니다.

`getRole()`에서 이거랑 대응되는걸 반환하고 있는데, 문자열로 나타내기 싫으실거라면 `getRole()`의 반환값을 enum으로 변경해주세요.

2024-09-23 01:30 UTC, CubeDr commented on app/components/LogIn.tsx
> +  const [status, setStatus] = useState<SignInStatus>(SignInStatus.NONE);
`role`, `setRole`

2024-09-23 01:30 UTC, CubeDr commented on app/layout.tsx
> +          <LogIn/>
리포맷 부탁드립니다.

2024-09-24 14:26 UTC, judiking1 commented on app/components/LogIn.tsx
> +    </>
![image](https://github.com/user-attachments/assets/d7a9c0a5-b317-4bc3-863d-67b7ccb74701)

2024-09-27 00:47 UTC, CubeDr approved these changes

2024-09-27 01:53 UTC, merged