#1 Auth
reboot-badminton/reboot-homepage pull request #21
Opened 2024-09-22 11:49 UTC by judiking1

2024-09-22 13:40 UTC, CubeDr requested changes

2024-09-22 13:40 UTC, CubeDr commented on app/layout.tsx
> +  });
이렇게 하면 렌더링 될 때마다 호출되니 `useState`랑 `useEffect` 써서 호출해주세요

2024-09-22 13:40 UTC, CubeDr commented on app/layout.tsx
> +          <LogIn uid={tokens?.decodedToken.uid}/>
로그인 정보는 여기저기서 많이 사용하게 될 것 같은데 이렇게 props로 넘기는 방법 말고 다른 방법을 생각해봐야 할 것 같습니다. 로그인 정보 쓸 때마다 props로 일일이 가져오려면 너무 번거로워질 것 같습니다. 위에 `tokens`를 생성하는 부분을 `Provider` 랑 `Context` 같은걸로 분리하면 어떨까 싶습니다.
https://velog.io/@mjieun/Next.js-React-Context%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EC%83%81%ED%83%9C%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

2024-09-22 13:40 UTC, CubeDr commented on app/manage/AccessControl.tsx
> +  }, [router]);
`setLoading`에도 dependency 걸어주세요

2024-09-22 13:40 UTC, CubeDr commented on app/manage/AccessControl.tsx
> +export default function AccessControl({ children }: { children: ReactNode }) {
이건 특정 사용자들에게만 공개하고 싶은 페이지에 범용적으로 사용할 수 있는 컴포넌트인 것 같습니다.

나중에 가면 다른 사례들도 생기겠지만, 지금은 허용하는 role만 props로 받아올 수 있게 합시다.

registration의 경우, 다음처럼 쓸 수 있게 하면 될 것 같습니다.

```
<AccessControl allowedRoles={['admin', 'manager']}>
...
</AccessControl>
```

2024-09-22 13:40 UTC, CubeDr commented on app/manage/AccessControl.tsx
> +        router.push('/');
다른 페이지에서 넘어왔을 수도 있으니 `router.back()`을 사용합시다.

2024-09-22 13:40 UTC, CubeDr commented on app/manage/slots/Slot.tsx
> +  isAdmin: boolean;
여기도 결국 로그인 정보 가져오는 부분이니까 props 말고 `Context`로 가져와주세요.

2024-09-22 13:40 UTC, CubeDr commented on app/manage/slots/TimeTable.tsx
> +  isAdmin: boolean;
`Context`로 읽어오면 이런 변경이 필요하지 않습니다.
특정 상황에서만 사용하는 데이터는 props로 넘기는게 유리하겠지만, 로그인 정보는 너무 범용적인 데이터라 `Context`로 관리하는게 나아보입니다.

2024-09-22 13:40 UTC, CubeDr commented on app/manage/slots/getSlot.ts
> +import { firestore } from '@/firebase';
지워주세요

2024-09-22 13:40 UTC, CubeDr commented on app/manage/slots/page.tsx
> +    <AccessControl>
여기도 마찬가지로 `allowedRoles` 명시해서 넘기는걸로 해줍시다.

2024-09-22 13:40 UTC, CubeDr commented on firebase.ts
> +export const firestore = getFirestore(app);
위치 바꾸신 이유가 있습니까?

2024-09-22 13:40 UTC, CubeDr commented on middleware.ts
> +import { clientConfig, serverConfig } from './config';
밑에 빈 줄 추가해주세요

2024-09-22 13:40 UTC, CubeDr commented on middleware.ts
> +const PUBLIC_PATHS = ['/signup', '/login'];
밑에 빈 줄 추가헤주세요

2024-09-22 13:40 UTC, CubeDr commented on middleware.ts
> +        });
`AccessControl` 호출하는 페이지에서도 실패 시 fallback 하는 경로를 명시했었는데, 이 부분이랑 차이점이 뭔가요?

2024-09-22 17:10 UTC, judiking1 commented on app/layout.tsx
> +  });
cookies() 는 서버사이드에서 실행가능

2024-09-22 17:14 UTC, judiking1 commented on app/layout.tsx
> +          <LogIn uid={tokens?.decodedToken.uid}/>
cookies() 는 서버사이드에서 실행가능한데, Context 는 클라이언트 사이드에서 사용가능해서 양립되고 있습니다.

Provider에서는 로그인 정보로 user.uid 값을 가져오는게 좋지 않을까 싶습니다.

2024-09-22 17:57 UTC, judiking1 commented on middleware.ts
> +        });
얘는 토큰이 없거나 올바른 로그인정보가 없으면,
특정 페이지로 요청할 때 (예로) `if(request.nextUrl.pathname === '/register')` 
login 페이지로 보내겠다는 뜻입니다.

2024-09-27 00:42 UTC, CubeDr requested changes

2024-09-27 00:42 UTC, CubeDr commented on middleware.ts
> +        });
`AccessControl`도 마찬가지 아닌가요?? 토큰이 없거나 올바른 로그인 정보가 없으면 `uid`가 `null`이 되고, 로그인 페이지로 가지 않나요?

2024-09-28 14:39 UTC, judiking1 commented
대신 middleware는 role을 확인할 수 없어서 AccessControl에서 role도 확인하는것..

2024-09-29 14:14 UTC, CubeDr requested changes

2024-09-29 14:14 UTC, CubeDr commented on app/register/page.tsx
> +      <div  className='p-2'>
`div` 다음에 공백 한 칸으로 줄여주세요

2024-09-29 14:14 UTC, CubeDr commented on middleware.ts
> -      }
이 부분 살려주세요

2024-09-29 14:14 UTC, CubeDr commented on middleware.ts
> +    handleInvalidToken: async (reason) => {
아무 역할도 하지 않습니다. 삭제해주세요.

2024-09-29 14:14 UTC, CubeDr commented on middleware.ts
> +    handleError: async (error) => {
AccessControl에서 잡히므로 삭제해주세요

2024-09-29 14:14 UTC, CubeDr commented on firebase.ts
> +import { clientConfig } from './config';
`firebase-config`랑 `config`랑 무슨 차이입니까?

2024-09-29 14:23 UTC, judiking1 commented on middleware.ts
> -      }
이거 있으면 회원가입 로그인페이지로 들어가려해도 계속 홈페이지로 이동되더라

2024-09-29 14:26 UTC, judiking1 commented on firebase.ts
> +import { clientConfig } from './config';
.env.local 파일에 있는 값들 보면 좀 다른데, FIREBASE_ADMIN_PRIVATE_KEY랑 FIREBASE_ADMIN_CLIENT_EMAIL 도 사용하는 중이긴함..

2024-09-29 14:30 UTC, CubeDr commented on firebase.ts
> +import { clientConfig } from './config';
값이 다른 건 알겠는데 두 개 역할이 어떻게 달라서 바꾸신건게요?

2024-09-29 14:33 UTC, judiking1 commented on app/manage/AccessControl.tsx
> +    }
이거 useEffect 분리하니까, 로그인없이 관리자페이지나 레슨신청 들어가면 login 페이지로 안 가고
그냥 계속 홈페이지로 보내지게돼

2024-09-29 14:46 UTC, judiking1 commented on firebase.ts
> +import { clientConfig } from './config';
사실 이전에 참고했다던 블로그에서 사용법을 그대로 가져와서 사용했습니다.

2024-09-29 15:10 UTC, CubeDr requested changes

2024-09-29 15:10 UTC, CubeDr commented on app/components/AuthProvider.tsx
> +  const [uid, setUid] = useState<string | null>(initialUid);
`initialUid`가 필요한가요? `initialUid`는 컴포넌트 생성시에 바로 설정이 되는데, `role`은 네트워크를 타야 해서 네트워크 시간 만큼 `uid`랑 `role`의 싱크가 깨집니다. 이걸 감수하고서라도 `initialUid`를 먼저 설정해놔야 하는 케이스가 있나요?

2024-09-29 15:10 UTC, CubeDr commented on app/components/LogIn.tsx
> +      )}
`!uid`로 묶어줍시다.

```
{!uid &&
  <>
    <Button text="로그인" onClick={() => router.push('/login')} />
    <Button text="회원 가입" onClick={() => router.push('/signup')} />
  </>
}
```

2024-10-06 05:43 UTC, closed without merging