회원가입에 개인정보 동의 추가
reboot-badminton/reboot-homepage pull request #38
Opened 2024-10-19 16:41 UTC by judiking1

![image](https://github.com/user-attachments/assets/8c877f8b-6d85-4349-9009-d64f26bacae0)

2024-10-19 17:30 UTC, CubeDr requested changes

2024-10-19 17:30 UTC, CubeDr commented on app/signup/UserDataSignup.tsx
> +      const privacyConsentDate = new Date();
아래에 인라인시켜주고, 문자열 말고 epoch 시간을 씁시다.
앞으로 시간 다뤄야 하는 건 epoch로 통일합시다.

2024-10-19 17:30 UTC, CubeDr commented on app/signup/UserDataSignup.tsx
> +        privacy: privacyConsentDate.toISOString(),
`privacy: new Date().getTime(),`

2024-10-19 17:30 UTC, CubeDr commented on app/signup/UserDataSignup.tsx
> +  const [isPrivacyChecked, setIsPrivacyChecked] = useState(false);
`checked`라고 하면 동의에 체크한 것 같아 헷갈립니다.

`didOpenPrivacyPage` 정도로 변경해주세요.

2024-10-19 17:30 UTC, CubeDr commented on app/signup/UserDataSignup.tsx
> +          disabled={!isPrivacyChecked}
disabled된 상태가 잘 구분이 되나요? 구분이 된다면 스샷 첨부 부탁드리고, 아니면 구분 되게 수정 후 스샷 부탁드립니다.

2024-10-20 12:50 UTC, judiking1 commented on app/signup/UserDataSignup.tsx
> +          disabled={!isPrivacyChecked}
약관 열기 전
![image](https://github.com/user-attachments/assets/318c3400-977d-48bb-91cd-2c880e7ea55c)

약관 연 후
![image](https://github.com/user-attachments/assets/b9feb681-99f1-459f-9697-e92a40b0dbd8)

2024-10-20 15:22 UTC, CubeDr requested changes

2024-10-20 15:22 UTC, CubeDr commented on app/signup/UserDataSignup.tsx
> +          className={`bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block`}
이건 왜 바꾸신거죠? 원래대로 큰 따옴표 써주시는 게 나아보입니다.

2024-10-20 15:22 UTC, CubeDr commented on app/signup/UserDataSignup.tsx
> +            약관 보기(필수)
띄어쓰기 넣어주시죠. `약관 보기 (필수)`

2024-10-26 12:51 UTC, merged