네이버지도 추가
reboot-badminton/reboot-homepage pull request #39
Opened 2024-10-20 17:32 UTC by judiking1

![image](https://github.com/user-attachments/assets/4b6f0c07-f343-4ed0-b63e-4e1b10f0c8a7)

2024-10-21 10:04 UTC, CubeDr commented
디자인 조금만 더 신경써주실 수 있나요?

1. "오시는 길" 이 드렸던 예시 스크린샷처럼 왼쪽 정렬 되어 있고, 그 왼쪽에 blue-300 정도로 제목이라는 걸 알려주는 것이 좋을 것 같습니다.
2. 주소, TEL, Phone 줄 사이 간격 통일시켜주세요. 지금보다 조금 더 좁아져도 괜찮을 것 같습니다.
3. 주소, TEL, Phone 이후 콜론과 실제 내용 사이에 공백 추가해주세요
4. 위치별 거리 안내는 조금 더 컴팩트하게 보여줄 수 있을 것 같습니다. 표 형식으로 해서 1) 이동 수단 (차량, 지하철, 버스), 2) 출발지, 3) 소요 시간으로 보여줍시다.

2024-10-23 17:33 UTC, judiking1 commented
![image](https://github.com/user-attachments/assets/a79c1baa-4f72-40f1-8c36-59e1d8ce1579)

2024-10-24 12:05 UTC, CubeDr requested changes
모바일처럼 화면 좁아졌을 때 지도와 오는 길이 세로로 배치되게 부탁드립니다.

2024-10-24 12:05 UTC, CubeDr commented on app/components/Location.tsx
> +              <MdSportsTennis />
배드민턴의 숙적인 테니스는 뺍시다

2024-10-24 12:05 UTC, CubeDr commented on app/components/NaverMap.tsx
> +        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_ID}&submodules=geocoder`}
깃헙 액션에서 환경 변수를 읽는 걸 잘 모르겠더라구요.
일단은 config에 하드코딩 해 놓읍시다. public이니까 괜찮을 거라 생각합니다.
아니면 혹시 네이버 키는 공개되면 안되나요?

2024-10-24 12:05 UTC, CubeDr commented on app/components/NaverMap.tsx
> +    if (COORDINATES && scriptLoaded) {
반전시켜서 준비되지 않았을 때 return 하는 걸로 바꿔주세요.

2024-10-24 13:55 UTC, judiking1 commented on app/components/NaverMap.tsx
> +        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_ID}&submodules=geocoder`}
네이버 키는 공개되면 안될것같아 내 개인 카드 등록해놓고 쓰는거라
지도 읽는 서비스 횟수 넘어가면 결제될듯
카톡으로 줄까?

2024-10-24 16:23 UTC, judiking1 commented
![image](https://github.com/user-attachments/assets/fbee495a-5553-44da-90bf-b0cd4af358af)

2024-10-25 05:51 UTC, CubeDr commented on app/components/NaverMap.tsx
> +        src={`https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_ID}&submodules=geocoder`}
음 그렇군요. 그럼 이거 올라갔을 때 환경변수 잘 읽을 수 있는지 확인 부탁드립니다.

2024-10-25 05:55 UTC, CubeDr requested changes

2024-10-25 05:55 UTC, CubeDr commented on app/components/NaverMap.tsx
> +    if (!COORDINATES || !scriptLoaded) {
`COORDINATES`는 상수니까 검사 안하셔도 될 것 같습니다.

2024-10-25 05:55 UTC, CubeDr commented on app/components/NaverMap.tsx
> +  }, [COORDINATES, scriptLoaded]);
dependency에서 `COORDINATES` 빼도 될 것 같은데 warning 뜨나요?

2024-10-25 05:55 UTC, CubeDr commented on app/components/NaverMap.tsx
> +    if (!mapRef.current) {
mapRef와 markerRef에 값이 없는게 예외상황이니 다음과 같이 수정합시다.
```
if (!mapRef.current) {
    mapRef.current = new window.naver.maps.Map(MAPID, mapOptions);
}

if (!markerRef.current) {
    markerRef.current = ...
}

mapRef.current.setCneter(position);
...
```

2024-10-26 15:14 UTC, merged